# Generated by Django 3.0.3 on 2020-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('roomReserved', models.CharField(default='null', max_length=255, verbose_name='Room reserved')),
                ('fromDate', models.DateTimeField(blank=True, null=True)),
                ('toDate', models.DateTimeField(blank=True, null=True)),
                ('employees', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoomInBuilding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meetingRoomTitle', models.CharField(max_length=255, verbose_name='Title')),
                ('isAvailable', models.BooleanField(default=True)),
                ('roomSize', models.IntegerField(default=0)),
            ],
        ),
    ]
