# Generated by Django 3.0.3 on 2020-02-08 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='employees',
            field=models.TextField(default=datetime.datetime(2020, 2, 8, 14, 10, 53, 526663, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='fromDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 14, 10, 57, 275780, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='toDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 14, 11, 1, 501622, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
